# Project-wide Gradle settings.
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.defaults.buildfeatures.buildconfig=false
kotlin.incremental=true

# Ajustes de memoria y estabilidad
org.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx2g
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=true
